<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.29.2" />
    <PackageReference Include="Azure.Storage.Queues" Version="12.27.1" />
    <PackageReference Include="Azure.Data.Tables" Version="12.13.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="StorageExplorer.Tests" />
    <InternalsVisibleTo Include="StorageExplorer.IntegrationTests" />
  </ItemGroup>

</Project>
